"""The Conifer gateway SDK for Python. Standard library only.

    from conifer_sdk import Conifer, ChatRequest
    answer = Conifer().chat(ChatRequest(model="auto", messages=[...]))
    answer.text, answer.receipt.cost_nano_usd
"""

__version__ = "0.2.0"

from .client import (
    Conifer,
    DEFAULT_BASE_URL,
    DEFAULT_TIMEOUT_SECONDS,
    MIN_DEFER_WINDOW_SECONDS,
    MAX_SERVER_FALLBACK_MODELS,
    decode_vector,
    server_fallback_header,
    to_deferred_job,
    with_cost,
    turn_identity,
    parse_frame,
    resolve_base_url,
    route_body,
    to_route_decision,
)
from .errors import (
    ConiferAuthError,
    ConiferBadRequestError,
    ConiferCapabilityError,
    ConiferByokKeyError,
    ConiferConflictError,
    ConiferConnectionError,
    ConiferCostCeilingError,
    ConiferKeySpendCapError,
    ConiferError,
    ConiferModelNotFoundError,
    ConiferPaymentError,
    ConiferPortabilityError,
    ConiferRateLimitError,
    ConiferTimeoutError,
    ConiferUnavailableError,
    ConiferUpstreamError,
    error_from,
)
from .receipt import CostComponents, Receipt, nano_usd_to_usd_string, read_receipt
from .portability import (
    attribution_from_openrouter,
    ceiling_from_policy,
    conifer_openai_compatible_config,
    from_helicone_headers,
    from_openrouter,
    from_vercel_provider_options,
    parse_fallbacks,
)
from .receipts import (
    ObservedReceipt,
    ReceiptCollector,
    ReceiptTotal,
    SpendBudget,
    SpendBudgetExceeded,
)
from .types import (
    Balance,
    DeferredJob,
    TERMINAL_JOB_STATUSES,
    is_terminal_job,
    CatalogModel,
    ChatRequest,
    Completion,
    Embedding,
    EmbeddingsRequest,
    EmbeddingsResponse,
    ROUTE_POLICIES,
    RouteDecision,
    RouteRequest,
    vector_of,
)

__all__ = [
    "Conifer",
    "DEFAULT_BASE_URL",
    "DEFAULT_TIMEOUT_SECONDS",
    "resolve_base_url",
    "parse_frame",
    "decode_vector",
    "ReceiptCollector",
    "ObservedReceipt",
    "ReceiptTotal",
    "SpendBudget",
    "SpendBudgetExceeded",
    "MIN_DEFER_WINDOW_SECONDS",
    "MAX_SERVER_FALLBACK_MODELS",
    "server_fallback_header",
    "DeferredJob",
    "TERMINAL_JOB_STATUSES",
    "is_terminal_job",
    "to_deferred_job",
    "with_cost",
    "turn_identity",
    "Embedding",
    "EmbeddingsRequest",
    "EmbeddingsResponse",
    "vector_of",
    "ConiferError",
    "ConiferAuthError",
    "ConiferPaymentError",
    "ConiferCostCeilingError",
    "ConiferKeySpendCapError",
    "ConiferBadRequestError",
    "ConiferCapabilityError",
    "ConiferModelNotFoundError",
    "ConiferConflictError",
    "ConiferByokKeyError",
    "ConiferRateLimitError",
    "ConiferUpstreamError",
    "ConiferUnavailableError",
    "ConiferTimeoutError",
    "ConiferConnectionError",
    "ConiferPortabilityError",
    "error_from",
    "Receipt",
    "CostComponents",
    "read_receipt",
    "nano_usd_to_usd_string",
    "ChatRequest",
    "Completion",
    "CatalogModel",
    "Balance",
    "ROUTE_POLICIES",
    "RouteDecision",
    "RouteRequest",
    "route_body",
    "to_route_decision",
    "from_openrouter",
    "attribution_from_openrouter",
    "from_helicone_headers",
    "from_vercel_provider_options",
    "conifer_openai_compatible_config",
    "ceiling_from_policy",
    "parse_fallbacks",
]

