#!/usr/bin/env bash
# Regenerate the `sdk-public` branch: a FILTERED subtree split of `sdk/`.
#
# The public mirror (ConiferKit/use-conifer) is this branch, pushed to its
# `main`. It is generated, never hand-edited: edit `sdk/` on `main`, then run
# this.
#
# Why filtered rather than `git subtree split --prefix=sdk`: some paths under
# `sdk/` are deliberately NOT public. A plain subtree split published them
# (`agents/` shipped in the mirror at fcb7dd7 by accident). Every exclusion
# below is load-bearing; removing one publishes code.
set -euo pipefail

cd "$(dirname "$0")/../.."   # workspace root

SOURCE_BRANCH="${SOURCE_BRANCH:-main}"
SPLIT_BRANCH="${SPLIT_BRANCH:-sdk-public}"

# Paths under sdk/ that must never reach the public mirror. Top-level entries
# only (this filters the sdk/ tree's direct children).
EXCLUDE=(
  # conifer-agents: unpublished, unapproved for release. See sdk/AGENTS.md.
  agents
  # Entirely about sdk/agents, so it names a package the mirror does not carry.
  AGENTS.md
)

src_commit=$(git rev-parse "$SOURCE_BRANCH")
src_tree=$(git rev-parse "$SOURCE_BRANCH:sdk")

# Build the filtered tree by dropping the excluded top-level entries.
listing=$(git ls-tree "$src_tree")
for name in "${EXCLUDE[@]}"; do
  listing=$(printf '%s\n' "$listing" | grep -v "$(printf '\t')${name}\$" || true)
done
filtered_tree=$(printf '%s\n' "$listing" | git mktree)

# Verify the exclusions actually took, recursively. A typo in EXCLUDE would
# otherwise silently publish the thing it was meant to hold back.
for name in "${EXCLUDE[@]}"; do
  if git ls-tree -r --name-only "$filtered_tree" | grep -q "^${name}\(/\|\$\)"; then
    echo "FATAL: '$name' survived the filter" >&2
    exit 1
  fi
done

parent=$(git rev-parse --verify --quiet "$SPLIT_BRANCH" || true)

if [ -n "$parent" ] && [ "$(git rev-parse "$parent^{tree}")" = "$filtered_tree" ]; then
  echo "sdk-public is already at this tree; nothing to do."
  exit 0
fi

msg="sdk: regenerate the public mirror from ${SOURCE_BRANCH} @ $(git rev-parse --short "$src_commit")

Generated by sdk/scripts/public-split.sh. Do not hand-edit this branch.
Excluded from the split: ${EXCLUDE[*]}"

if [ -n "$parent" ]; then
  new=$(printf '%s' "$msg" | git commit-tree "$filtered_tree" -p "$parent")
else
  new=$(printf '%s' "$msg" | git commit-tree "$filtered_tree")
fi

git update-ref "refs/heads/$SPLIT_BRANCH" "$new"
echo "$SPLIT_BRANCH -> $(git rev-parse --short "$new")"
echo
echo "Publish with:"
echo "  git push https://github.com/ConiferKit/use-conifer $SPLIT_BRANCH:main"
